### ISSUE TITLE
add support for FORCESOLUTION (instead of CMTSOLUTION) in SPECFEM3D_GLOBE

### ISSUE THREAD

**Issue by carltape** [geodynamics/specfem3d_globe#270]
It would be useful to have the option of implementing a force, similar to what is available in SPECFEM3D (FORCESOLUTION instead of CMTSOLUTION). This implementation would be useful for ambient noise tests, for example. People have shown coherent signals for period up to 100s of seconds, so this would be nice to have at the global scale.

**Comment by komatits** [comment]
From Hom Nath @homnath :  

Reciprocal strain Green functions in SPECFEM3D Globe:

Dear all,

Some people were asking about the possibility of computing reciprocal strain Green functions in SPECFEM3D Globe (strain tensor recordings for a point force source). It appears to me that such a feature is not currently available in SPECFEM3D Globe. Have anybody ever computed those functions using SPECFEM3D Globe? Or is it worthwhile to add such a feature in SPECFEM3D Globe? It seems,  however, possible in SPECFEM3D Cartesian because it has FORCESOLUTION feature.

Any suggestions would be greatly appreciated!

Thanks,
Hom Nath

**Comment by komatits** [comment]
Dear Hom Nath, dear all,

That would be very useful. It is worth adding such an option. This is indirectly related to https://github.com/geodynamics/specfem3d_globe/issues/270

Best regards,
Dimitri.

**Comment by komatits** [comment]
The FORCESOLUTION option is implemented but not tested (and hidden in constants.h, should of course be moved to the Par_file or the source file).

**Comment by komatits** [comment]
From Qinya Liu @liuqinya :   

The force solution is actually much easier than the moment-tensor
solution, so there should be no problem implementing it. I think the
part that needs more thinking is how  (and where) to save the
wavefield.  If you want to store the field on a regular grid, it may
help to refer to Elliott's earlier commits on saving kernels on a
regular grid.  On the other hand, Vala and I have been thinking along
a similar line for fast global source inversions. It will be great if
we can together implement it as part of the regular release.

**Comment by komatits** [comment]
From Hom Nath @homnath :  

Great idea! Thank you for your feedback/suggestions! I agree that the point force implementation should not be that difficult because it is already implemented in Cartesian version. I see one problem. For finite/spectral element method, the derivative of a primary variable is discontinuous across the element boundaries. That means strain/stress field will be discontinuous across the element boundary. In classical FEM, so-called strain smoothing procedure is employed in order to obtain the smooth and accurate strain/stress field. We could implement the similar technique. But for the first stage, we could first implement point force and see how the simply interpolated strain compares with the finite difference method.

I will see if I can quickly implement FORCESOLUTION in the Globe version.

Best,
Hom Nath

**Comment by komatits** [comment]
Done by Hom Nath @homnath
