### ISSUE TITLE
Bugs in subroutine save_kernels_source_derivatives()

### ISSUE THREAD

**Issue by taotaokai** [geodynamics/specfem3d_globe#459]
At lines 745-755 in src/specfem3D/save_kernels.F90

```fortran
sloc_der(:,irec_local) = matmul(transpose(nu_source(:,:,irec_local)),sloc_der(:,irec_local)) 

moment_der(:,:,irec_local) = matmul(matmul( &
transpose(nu_source(:,:,irec_local)),moment_der(:,:,irec_local)), nu_source(:,:,irec_local))
```

should be

```fortran
sloc_der(:,irec_local) = matmul(nu_source(:,:,irec_local),sloc_der(:,irec_local)) 

moment_der(:,:,irec_local) = matmul(matmul( &
nu_source(:,:,irec_local)),moment_der(:,:,irec_local), transpose(nu_source(:,:,irec_local)))
```
. The **nu_source** is the rotation matrix from ECEF to local N-E-UP as defined in src/locate_sources.f90:281-317. Also a simple synthetic test confirms this problem.

**Comment by komatits** [comment]
Thanks! Could you email me the modified file? I will then make the 
change on the official Git server (or if you want you can easily do it 
yourself, just follow 
https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM ).

You can maybe put your comment below (*nu_source* is the rotation matrix 
from ECEF to local N-E-UP as defined in src/locate_sources.f90) as a 
comment in the modified file.

Thank you very much,
Dimitri.

On 02/04/2016 04:43 PM, taotaokai wrote:
> At lines 745-755 in src/specfem3D/save_kernelsF90
>
> sloc_der(:,irec_local)=  matmul(transpose(nu_source(:,:,irec_local)),sloc_der(:,irec_local))
>
> moment_der(:,:,irec_local)=  matmul(matmul( &
> transpose(nu_source(:,:,irec_local)),moment_der(:,:,irec_local)), nu_source(:,:,irec_local))
>
> should be
>
> sloc_der(:,irec_local)=  matmul(nu_source(:,:,irec_local),sloc_der(:,irec_local))
>
> moment_der(:,:,irec_local)=  matmul(matmul( &
> nu_source(:,:,irec_local)),moment_der(:,:,irec_local),transpose(nu_source(:,:,irec_local)))
>
> The *nu_source* is the rotation matrix from ECEF to local N-E-UP as
> defined in src/locate_sourcesf90:281-317 Also a simple synthetic test
> confirms this problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/459>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by taotaokai** [comment]
Thank you, I just sent the pull request.

**Comment by komatits** [comment]
Thanks! I have just accepted it.

Dimitri.

On 02/09/2016 02:25 AM, taotaokai wrote:
> Thank you, I just sent the pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d_globe/issues/459#issuecomment-181658974>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKbZgQrzBq3rLG3WgcSqNw7dpk07Xks5piTd1gaJpZM4HTep7.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
It seems the original code was right (see comment by Qinya Liu below), thus let me reopen this issue.

**Comment by komatits** [comment]
From Qinya Liu, Toronto Univ:    @taotaokai 

I think we need to be a bit careful here, because these derivatives
are basically derivatives of the misfit function phi with respect to
source parameters, which means, if the nu is the rotation matrix that
transforms coordinates from the global system (x,y,z) to the local
coordinate system (N,E,V), e.g., the moment tensor is transformed as

M_L = \nu * M_g * \nu^T,

then the derivative should be transformed as

\partial{\phi}{M_L} = \nu^T \partial{\phi}{M_g} \nu

which is in the opposite sense from the transformation of M, and hence
the original implementation. It will be interesting to see what the
synthetic test is that confirms the other way.

**Comment by komatits** [comment]
Hi Qinya @liuqinya ,

Thanks a lot. I have informed the user ( @taotaokai ) and have thus reverted the change for now, until we get confirmation tests.

I have also cut and pasted your email below as a comment in that routine, so that people have a clear explanation in the source code.

Thanks!
Dimitri.

**Comment by komatits** [comment]
This seems to be closed as well.
