### ISSUE TITLE
Make and run the meshfem3D

### ISSUE THREAD

**Issue by PhilTsao** [geodynamics/specfem3d_globe#600]
# STEP:
$configure;
$make meshfem3D
$mpirun -np 64 ./bin/meshfem3D 

# ERRO:
There are not enough slots available in the system to satisfy the 64 slots
that were requested by the application:
  ./bin/meshfem3D

Either request fewer slots for your application, or make more slots available
for use.

When I used 2 instead of 64，this problem still exists. please help me.(sorry my English is not very good)

**Comment by komatits** [comment]
Dear PhilTsao,

Thank you for your message. This problem is likely due to MPI on your 
machine, and thus independent of SPECFEM. You can try with an MPI test 
program (for instance http://mpitutorial.com/tutorials/mpi-hello-world/ 
or https://www.eecis.udel.edu/~pollock/367/manual/node18.html ) and then 
contact the system administrator of your machine if that simple test 
fails as well.

Best regards,
Dimitri.

On 10/31/2017 11:05 AM, PhilTsao wrote:
> 
>   STEP:
> 
> $configure;
> $make meshfem3D
> $mpirun -np 64 ./bin/meshfem3D
> 
> 
>   ERROR:
> 
> There are not enough slots available in the system to satisfy the 64 slots
> that were requested by the application:
> ./bin/meshfem3D
> 
> Either request fewer slots for your application, or make more slots 
> available
> for use.
> 
> When I used 2 instead of 64，this problem still exists. please help 
> me.(sorry my English is not very good)
> 

-- 
Dimitri Komatitsch, CNRS Research Director (DR CNRS)
Laboratory of Mechanics and Acoustics, Marseille, France
http://komatitsch.free.fr

**Comment by PhilTsao** [comment]
Dear  komatits 
Thank you very for you help! And  this problem is due to MPI on my machine indeed, because I just run the program on single machine. 


Best regards,
PhilTsao

**Comment by PhilTsao** [comment]
Dear Dimitri,
Thank you very much for you help! And this problem is due to MPI on my machine indeed, because I just run the program on single machine. 


Best regards,
PhilTsao
