### ISSUE TITLE
Build error with gcc compiler: Array out-of-bounds reference error

### ISSUE THREAD

**Issue by t-karatsu** [geodynamics/specfem3d_globe#717]
A following error occured when building specfem3d with gcc compiler in my environment.
```
$ configure --prefix=/my_build_env --enable-openmp --disable-double-precision
$ make -j16
...
/my_env/gfortran -g -O2  -fopenmp -DUSE_OPENMP    -std=gnu -fimpli
cit-none -frange-check -fmax-errors=10 -pedantic -pedantic-errors -Waliasing -Wampersand -Wcharacter-truncation -Wlin    
e-truncation -Wsurprising -Wno-tabs -Wunderflow -ffpe-trap=invalid,zero,overflow -Wunused -Werror -O3 -finline-functi    
ons -J./obj -I./obj -I.  -I. -I./setup -c -o obj/compute_kernels.solverstatic.o src/specfem3D/compute_kernels.F90
...
src/specfem3D/compute_kernels.F90:529:32:

src/specfem3D/compute_kernels.F90:517:34:

     do ispec = 1, NSPEC_OUTER_CORE
                                  2
src/specfem3D/compute_kernels.F90:529:32:

         rho_kl_outer_core(INDEX_IJK,ispec) = rho_kl_outer_core(INDEX_IJK,ispec) + deltat * (gradxyz(1) + gradxyz(2)
 + gradxyz(3))
                                1
Error: Array reference at (1) out of bounds (1120 > 1) in loop beginning at (2) [-Werror]
...
src/specfem3D/compute_kernels.F90:536:69:

src/specfem3D/compute_kernels.F90:517:34:

     do ispec = 1, NSPEC_OUTER_CORE
                                  2
src/specfem3D/compute_kernels.F90:536:69:

         alpha_kl_outer_core(INDEX_IJK,ispec) = alpha_kl_outer_core(INDEX_IJK,ispec) + deltat * div_displ * b_div_dis
pl
                                                                     1
Error: Array reference at (1) out of bounds (1120 > 1) in loop beginning at (2) [-Werror]
f951: all warnings being treated as errors
make: *** [src/specfem3D/rules.mk:344: obj/compute_kernels.solverstatic.o] Error 1
make: *** Waiting for unfinished jobs....
```
The current environment has no GPU, so `cuda` and `opencl` are disabled.
I used default parameters on `DATA/Parfile`.
(`SIMULATION_TYPE` = 1, `SAVE_FORWARD` = .false.)

The above error is occurring in the function `compute_kernels`, which called from following files
・src/specfem3D/iterate_time.F90
・src/specfem3D/iterate_time_undoatt.F90

I can avoid the error by removing `-Werror` from `DEF_FFLAGS`, but is this the correct way to avoid this problem?

In my environment, I get following values: 
```
NSPEC_OUTER_CORE: 1120
NSPEC_OUTER_CORE_ADJOINT: 1
```
From these values, it is inevitable that array out-of-bounds reference error will occur.

**Comment by danielpeter** [comment]
thanks for reporting. 

the warning can be ignored, but since there is `-Werror`, the compilation stops. you could either remove the `-Werror` or the `-frange-check` flag.

anyway, i saw you were testing an older, tagged version 7.0.2 using a default compilation. this compilation issue seems to be fixed in the current devel version. i will soon release and tag that one as new master version 8.0.0. you could either update to it when available or change the configuration setup or remove the `-Werror` flag.

a basic configuration setup example, working with GCC compilers, could be: 
```
configure --prefix=/my_build_env --enable-openmp --enable-vectorization FLAGS_CHECK="-O3"
```
which should work and produce faster executables.

some more infos:
- "specfem3d" would rather refer to the Cartesian version (https://github.com/geodynamics/specfem3d) whereas "specfem3d_globe" would refer to this global version of the different SPECFEM packages. maybe you want to adapt this in your spark/ modifications.
- compilation for this globe version SPECFEM3D_GLOBE is still using a static array compilation. that is, changing the simulation setup (i.e., settings in DATA/Par_file) requires to re-compile the code. i'm not sure how this will affect your spark/ workflows - just to be aware.

**Comment by t-karatsu** [comment]
@danielpeter 
Thanks for your reply!
In versions up to 7.0.2, We'll remove `-Werror` when building with gcc compiler.
>"specfem3d" would rather refer to the Cartesian version (https://github.com/geodynamics/specfem3d) whereas "specfem3d_globe" would refer to this global version of the different SPECFEM packages. maybe you want to adapt this in your spark/ modifications. 

Thanks for checking the Spack changes.
I changed the name of OSS to "specfem3d-globe".
>compilation for this globe version SPECFEM3D_GLOBE is still using a static array compilation. that is, changing the simulation setup (i.e., settings in DATA/Par_file) requires to re-compile the code. i'm not sure how this will affect your spark/ workflows - just to be aware.

I'll consider a mechanism for building with the modified Par_file.
